version: '3'

services:
  db:
    container_name: inse2c_db
    build: ./pg
    ports:
      - 5432:5432
  
  server:
    container_name: inse2c_server
    build: ./server
    ports:
      - 5000:5000
